# config.yaml

debug:
  verbose: false

data:
  feature_path: ""
  gt_path: ""
  online_path_ft: ""
  online_path_gt: ""
  catch_path: ""
  log_transform: true
  train_time_beg: "2019-01-01"
  train_time_end: "2023-03-01"
  valid_time_beg: "2023-03-01"
  valid_time_end: "2023-08-01"

env:
  gpus_id: "0"

seed:
  random_seed: 666

exp:
  dir: "/home/sic/kk/Project/yx.nowcasting/aexp/debug"
  best_model_path: null

optim:
  name: "adamw"
  weight_decay: 0.2

lr:
  value: 0.001
  scheduler:
    name: "ReduceLROnPlateau"
    mode: "max"
    monitor: "ts50"
    threshold: 0.0004
    factor: 0.5
    patience: 5
    min_lr: 0.0001

train:
  batch_size: 1
  start_epoch: 0
  num_epochs: 100
  num_workers: 4
  visualize: false
  save_results: false
  early_stopping:
    patience: 20
    monitor: "ts50"
    mode: "max"

infer:
  batch_size: 1

loss:
  name: "WeightedMSELoss"  # WeightedMSELoss LabelBasedWeightedRegressionLoss
  weighted_mae_weight: 1.1
  base: 4
  normalize: false
  targets_div: 10
  use_mae: true
  nonzero_mean: true
  weights: [0.01, 0.5, 1, 5, 10] # [0.01, 0.5, 1.0, 5.0, 30.0] [0.01, 0.5, 1, 5, 10]


noise:
  use_noise: false
  noise_level: 0.001

model:
  name: "unet" # "temporal_model" "unet"
  dropout: 0.5